#include: package:pedantic/analysis_options.1.9.0.yaml
#analyzer:
#  enable-experiment:
#    - extension-methods

##analyzer:
##  exclude: [build/**]
###  为了不影响开发，暂时关闭，后面请大家可以打开这个选项进行检查
###  strong-mode:
###       隐式转换
###    implicit-casts: false
##  # 隐式dynamic
###    implicit-dynamic: false
##
### 参考：https://dart-lang.github.io/linter/lints/index.html
###  linter:
###    rules:
###      - annotate_overrides
###      - await_only_futures
###      - camel_case_types
###      - cancel_subscriptions
#
#
#analyzer:
#  exclude: [build/**]
##  strong-mode:
###     隐式转换
##    implicit-casts: false
##    # 隐式dynamic
##    implicit-dynamic: false
##  enable-experiment:
##    - extension-methods
##  errors:
##    # treat missing required parameters as a warning (not a hint)
##    missing_required_param: warning
##    # treat missing returns as a warning (not a hint)
##    missing_return: warning
##    # allow having TODOs in the code
##    todo: ignore
##    # Ignore analyzer hints for updating pubspecs when using Future or
##    # Stream and not importing dart:async
##    # Please see https://github.com/flutter/flutter/pull/24528 for details.
##    sdk_version_async_exported_from_core: ignore
##  # exclude:
##  #   - "bin/cache/**"
##  #   # the following two are relative to the stocks example and the flutter package respectively
##  #   # see https://github.com/dart-lang/sdk/issues/28463
##  #   - "lib/i18n/messages_*.dart"
##  #   - "lib/src/http/**"
##
##linter:
##  rules:
##    # these rules are documented on and in the same order as
##    # the Dart Lint rules page to make maintenance easier
##    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
##    - always_declare_return_types
