name: ax_flutter_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# 告警,用这个
publish_to: none

#analyzer:
#  enable-experiment:
#    - non-nullable

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 国际化
  flutter_localizations:
    sdk: flutter

  # 渐变颜色,微光动画效果
  shimmer: ^3.0.0
  css_colors: ^1.1.1
  #通用提示库flutter_image_compress
  fluttertoast: ^8.2.8
  # 加载网络图片 使用 https第一次加载页面,容易卡死,改为http,就可以了;等flutter升级
  # https://jhuo.ca/post/ocsp-stapling-letsencrypt/
  cached_network_image: ^3.2.2
  http: ^1.2.2
  dio: ^5.1.1
  #  http_parser: any
  #  json_annotation: any
  json_annotation: ^4.3.0
  #该软件包提供国际化和本地化功能，包括消息翻译，复数形式和性别，日期/数字格式和解析以及双向文本.
  #  intl: ^0.17.0
  #intl_utils是一个Dart库，可从ARB文件生成Dart本地化代码. 生成的代码依赖于Intl库.
  #  intl_utils: ^1.7.0
  #日期时间格式 另外一个库
  #  date_format: any
#  scoped_model: ^2.0.0
  # 1.0.0
  #  cupertino_icon: ^1.0.0
  # RxDart基于ReactiveX，由Dart标准库中Stream扩展而成，是一个为Dart语言提供响应式编程的库。
  rxdart: ^0.27.3
  #日志输出
  logger: ^2.0.2+1
  #日志在应用端输出
  #  logger_flutter: ^0.7.1
  #image保存相册
  #  image_gallery_saver: ^2.0.3
  #图片压缩
  #  flutter_luban: ^0.1.7
  #  #包信息
  #  package_info: ^0.4.0+13
  #  # 红点插件
  #  badges: ^1.1.0
  #  #多图选择
  #  multi_image_picker: ^4.6.1
  #  #时间选择
  #  flutter_cupertino_date_picker: ^1.0.23+1
  #  #通用选择器
  #  flutter_picker: 1.1.0
  #  flutter_webview_plugin: ^0.3.11

  # 准备停止维护,请使用谷歌的
  #  flutter_webview_plugin: ^0.3.11
  # listView 左右 侧滑
  #  slide_item: ^1.0.6

  #Hive是用纯Dart编写的轻量级且快速的键值数据库. 受Bitcask启发.
  hive: ^2.0.5
  hive_flutter: ^1.0.0

  #刷新组件
  #  flutter_easyrefresh: ^2.1.1
  #事件管理
  event_bus: ^2.0.0
  #谷歌字体
  google_fonts: ^6.2.1
  #  bloc: ^4.0.0

  flutter_bloc: ^8.0.0
  # 继承类,判断类是否相同
  equatable: ^2.0.5

  #  w_popup_menu: ^0.3.1

  #指纹
  local_auth: ^2.1.0

  #  binding_helper: 0.0.2

  photo_view: ^0.15.0
  #  redux主要由Store、Action、Reducer三部分组成
  #  Store用于存储和管理State
  #  Action用于用户触发的一种行为
  #  Reducer用于根据Action产生新的State

  #  flutter redux流程
  #  Widget通过StoreConnector绑定Store中的State数据
  #  Widget通过Action触发一种新的行为
  #  Reducer根据收到的Action更新State
  #  更新Store中的State绑定的Widget

  #  flutter_redux: 0.7.0
  redux: ^5.0.0
  #可以轻松地将Flutter集成到您现有的本机应用程序中.
  #FlutterBoost的理念是使用Flutter就像使用WebView一样容易.
  #在现有应用程序中，同时管理本机页面和Flutter页面并非易事.
  #FlutterBoost会为您解决页面分辨率问题. 您唯一需要关心的是页面名称（通常可以是URL）.
  #  flutter_boost: ^1.12.13
  #    git:
  #      url: 'https://github.com/alibaba/flutter_boost.git'
  #      ref: '1.12.13+2'

  #自定义相机
  camera: ^0.10.0+1
  #图片压缩
  flutter_image_compress: ^2.3.0
  # cell 侧滑删除
  #  flutter_swipe_action_cell: ^1.2.2
  # 状态管理,和google推荐的Provider 类似
  get: ^4.6.1
  web_socket_channel: ^3.0.1
  # 侧滑
  flutter_slidable: ^3.0.0
  sqflite: ^2.0.1
  # 设备权限
  permission_handler: ^11.3.1
  # 动画flutter_slidable
  lottie: ^3.1.2
  #截图
  screenshot: ^3.0.0
  # 启动图
  flutter_launcher_icons: ^0.13.0

  ##  ⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬ 谷歌组件 ⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬
  ## 谷歌维护的库 https://github.com/flutter/plugins

  #在 Flutter 1.17 发布大会上，Flutter 团队还发布了新的 Animations 软件包，
  #该软件包提供了实现新的 Material motion 规范的预构建动画。该软件包并不是内置的，而是第三方插件的形式。
  animations: ^2.0.5
  #  跳转指定位置
  scrollable_positioned_list: ^0.3.2
  # google推荐的Provider  Provider 代替 Provide 成为官方推荐的状态管理方式之一。
  #  provider: ^5.0.0
  provider: ^6.0.0
  #  device_info: ^2.0.2
  device_info_plus: ^10.1.2

  image_picker: ^1.1.2

  package_info_plus: ^8.0.2
  # 用于查找文件系统上的常用位置. 支持iOS和Android.fluttertoast
  path_provider: ^2.0.8

  #传感器插件
  #  sensors: 0.4.2

  # 在Android上包装ACTION_SEND Intent，在iOS上包装UIActivityViewController.
  #  share: 0.6.4+1

  # 包装NSUserDefaults（在iOS上）和SharedPreferences（在Android上），
  #为简单数据提供持久存储. 数据异步保存到磁盘.
  #这两个平台都不能保证在返回后将写操作持久化到磁盘，并且该插件不得用于存储关键数据.
  shared_preferences: ^2.0.11

  # Flutter插件，用于在移动平台中启动URL. 支持iOS和Android.
  url_launcher: ^6.0.17

  #官方插件：webview_flutter
  webview_flutter: ^4.0.7


    #  flutter_keychain: 1.0.0
    #适用于iOS，Android和Web的Flutter插件，用于在Widget表面上播放视频.
    #  video_player: 0.10.10

    # lutter插件，用于访问有关运行应用程序的设备电池的各种信息.
    #  battery: 1.0.0

    #该插件允许Flutter应用发现网络连接并进行相应配置. 它可以区分蜂窝连接和WiFi连接. 该插件适用于iOS和Android.
    #  connectivity: 0.4.8+5

    #应用内购买的Flutter插件. 公开用于通过App Store（在iOS上）和Google Play（在Android上）进行应用内购买的API.
    #  in_app_purchase: 0.3.3+1

    #这个Flutter插件使您可以管理应用程序的主屏幕快速动作并与之交互.
    #
  #快速操作是指iOS上的同义概念以及Android上的App Shortcuts API（在Android 7.1 / API 25级中引入）.
  #在Android的早期版本中运行此插件是安全的，因为它将产生Noop.
  #quick_actions: 0.4.0+4

  ## ⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬阿星组件 ⏬⏬⏬⏬⏬⏬⏬⏬⏬⏬
  #  ax_flutter_util:
  #    git:
  #      url: 'https://github.com/axinger/ax-flutter-util.git'
  #  #  ax_flutter_plugin:
  #  #    git:
  #  #      url: 'https://github.com/axinger/ax-flutter-plugin.git'
#  ax_flutter_toast:
#    git:
#      url: 'https://github.com/axinger/ax-flutter-toast.git'


  #  ax_flutter_util:
  #    path: ../ax-flutter-util
  #  ax_flutter_plugin:
  #    path: ../ax-flutter-plugin
  #  ax_flutter_toast:
  #    path: ../ax-flutter-toast

  ##=============================================================================##



#  flutter_boost:
#    git:
#      url: 'https://github.com/alibaba/flutter_boost.git'
#      ref: 'task/task_v1.9.1_support_hotfixes'

#  flutter_boost:
#    git:
#      url: 'https://github.com/alibaba/flutter_boost.git'
#      ref: ' 1.12.13'

#    flutter_boost: any
# 执行命令 flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/image/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  flutter_lints: ^5.0.0
  #这两个是dev的，不要放到上面去了哦
  #   build_runner: ^2.4.1
  json_serializable: ^6.0.1
  lints: ^2.0.0
  msix: ^3.16.10
#  hive_generator: ^0.7.0+2
##  dartx: ^0.2.0
##  quiver: '>=2.0.3 <2.1.0'
#
#
#  test: ^1.9.4
#  mockito: ^4.1.1
#  pedantic: ^1.9.0
#  dartx: ">=0.2.0 <1.0.0"
#  path: ^1.6.4
#  pointycastle: ^1.0.2
#
#  mobx_codegen: ^1.0.2
#  moor_generator: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: myIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/fonts/iconfont.json
    - assets/fonts/iconfont.svg
    - assets/fonts/iconfont.ttf
    - assets/image/
    - assets/image/album/
    - assets/lottie/

flutter_intl:
  enabled: true



# dart run msix:create
msix_config:
  display_name: flutter应用
  publisher_display_name: axinger公司
  identity_name: com.github.axinger.app1
  msix_version: 1.0.0.0
  #  logo_path: C:\path\to\logo.png
  #需要权限
  capabilities: internetClient, location, microphone, webcam
  desktop_shortcut: true  # 启用桌面快捷方式
